@startuml
autonumber
participant Client
database Postgres
participant "eel-backend"

Client ->> "eel-backend": PATCH api/v1/codes/<int:code_id>
"eel-backend" ->> Postgres: SELECT app_users WHERE id = ?
"eel-backend" ->> Postgres: SELECT user_roles WHERE user_id = ?
"eel-backend" ->> Postgres: SELECT registration_codes WHERE code_type = ?
"eel-backend" ->> Postgres: UPDATE registration_codes SET ...
"eel-backend" ->> Postgres: SELECT courses WHERE id = ?
"eel-backend" -->> Client: HTTP 200
@enduml
