@startuml
autonumber
participant Client
database Postgres
participant "eel-backend"

Client ->> "eel-backend": POST api/v1/auth/sessions
"eel-backend" ->> Postgres: SELECT app_users WHERE username = ?
"eel-backend" ->> Postgres: SELECT app_users WHERE email = ?
"eel-backend" ->> Postgres: SELECT user_roles WHERE user_id = ?
"eel-backend" ->> Postgres: SELECT app_users WHERE username = ?
"eel-backend" ->> Postgres: SELECT app_users WHERE email = ?
"eel-backend" ->> Postgres: SELECT app_users WHERE username = ?
"eel-backend" ->> Postgres: INSERT token_blacklist_outstandingtoken
"eel-backend" ->> Postgres: SELECT user_roles WHERE user_id = ?
"eel-backend" -->> Client: HTTP 200
@enduml
