# Generated by Django 5.2.11 on 2026-03-02 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("rubrics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="rubric",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="rubric_assessment_ids",
        ),
        migrations.AddField(
            model_name="question",
            name="grading_strategy",
            field=models.CharField(
                choices=[("AUTO", "Auto"), ("MANUAL", "Manual")], default="AUTO", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="rubrics.rubric",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentQuestionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order_index", models.IntegerField(default=0)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_groups",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_groups",
                        to="rubrics.rubric",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_question_groups",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="question_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="assessments.assessmentquestiongroup",
            ),
        ),
    ]
