# Generated by Django 5.2.11 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_rubric_cutover"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="scoring_policy",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("COMPLETION", "Completion")],
                default="STANDARD",
                max_length=32,
            ),
        ),
    ]
