# Generated by Django 5.2.11 on 2026-03-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_assessment_scoring_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodmeterquestion",
            name="question",
        ),
        migrations.AlterField(
            model_name="assessment",
            name="grading_mode",
            field=models.CharField(
                choices=[("AUTO", "Auto"), ("MANUAL", "Manual"), ("HYBRID", "Hybrid")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("MULTIPLE_CHOICE", "Multiple Choice"),
                    ("SHORT_ANSWER", "Short Answer"),
                    ("NUMBER_SCALE", "Number Scale"),
                ],
                db_column="type",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="MoodMeterLabel",
        ),
        migrations.DeleteModel(
            name="MoodMeterQuestion",
        ),
    ]
