# Generated by Django 5.2.11 on 2026-03-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_remove_moodmeterquestion_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
