# Generated by Django 5.2.11 on 2026-03-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_assessment_status_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="grading_mode",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto"),
                    ("MANUAL", "Manual"),
                    ("HYBRID", "Hybrid"),
                    ("MOOD_METER", "Mood Meter"),
                ],
                max_length=255,
            ),
        ),
    ]
