# Generated by Django 5.2.12 on 2026-04-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_assessment_archival_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("MULTIPLE_CHOICE", "Multiple Choice"),
                    ("SHORT_ANSWER", "Short Answer"),
                    ("NUMBER_SCALE", "Number Scale"),
                    ("MOOD_METER", "Mood Meter"),
                ],
                db_column="type",
                max_length=255,
            ),
        ),
    ]
