# Generated by Django 5.2.12 on 2026-04-02 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0008_alter_question_kind"),
        ("rubrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="rubrics.rubric",
            ),
        ),
    ]
