# Generated by Django 5.2.12 on 2026-04-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0010_alter_question_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
