# Generated by Django 5.2.12 on 2026-04-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0011_alter_assessment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="submission_mode",
            field=models.CharField(
                choices=[
                    ("DIGITAL", "Digital"),
                    ("UPLOAD_ONLY", "Upload Only"),
                    ("DIGITAL_WITH_UPLOAD", "Digital with Upload"),
                ],
                default="DIGITAL",
                max_length=32,
            ),
        ),
    ]
