"""
Assignment domain helpers — re-exported from sub-modules.
"""

from ._mutations import (
    ConflictError,
    ForbiddenError,
    _create_submissions_for_course,
    archive_assignment,
    create_assignment,
    purge_assignment,
    restore_assignment,
    update_assignment,
)
from ._archive_exports import (
    assignment_archive_artifact_to_dict,
    cleanup_assignment_archive_artifacts,
    generate_assignment_archive_artifact,
    get_assignment_archive_artifact,
)
from ._content import (
    add_assignment_question,
    add_assignment_teacher_criterion,
    add_assignment_teacher_criterion_level,
    assignment_content_to_dto,
    assignment_has_progressed_submissions,
    assignment_question_to_dto,
    delete_assignment_question,
    delete_assignment_teacher_criterion,
    delete_assignment_teacher_criterion_level,
    get_assignment_with_content,
    list_reusable_question_images,
    provision_submission_answers,
    reorder_assignment_questions,
    reorder_assignment_teacher_criteria,
    reorder_assignment_teacher_criterion_levels,
    snapshot_assignment_content,
    update_assignment_question,
    update_assignment_teacher_criterion,
    update_assignment_teacher_criterion_level,
)
from ._queries import (
    assignment_to_dto,
    get_assignment,
    list_by_course,
    list_for_user,
)

__all__ = [
    "ConflictError",
    "ForbiddenError",
    "_create_submissions_for_course",
    "add_assignment_question",
    "add_assignment_teacher_criterion",
    "add_assignment_teacher_criterion_level",
    "assignment_archive_artifact_to_dict",
    "assignment_content_to_dto",
    "assignment_has_progressed_submissions",
    "assignment_question_to_dto",
    "archive_assignment",
    "assignment_to_dto",
    "cleanup_assignment_archive_artifacts",
    "create_assignment",
    "delete_assignment_question",
    "delete_assignment_teacher_criterion",
    "delete_assignment_teacher_criterion_level",
    "generate_assignment_archive_artifact",
    "get_assignment",
    "get_assignment_archive_artifact",
    "get_assignment_with_content",
    "list_reusable_question_images",
    "list_by_course",
    "list_for_user",
    "provision_submission_answers",
    "reorder_assignment_questions",
    "reorder_assignment_teacher_criteria",
    "reorder_assignment_teacher_criterion_levels",
    "purge_assignment",
    "restore_assignment",
    "snapshot_assignment_content",
    "update_assignment",
    "update_assignment_question",
    "update_assignment_teacher_criterion",
    "update_assignment_teacher_criterion_level",
]
