@startuml
autonumber
participant Client
database Postgres
participant "eel-backend"

Client ->> "eel-backend": POST api/v1/user-batches
"eel-backend" ->> Postgres: SELECT app_users WHERE id = ?
"eel-backend" -->> Client: HTTP 201
@enduml
