# Generated by Django 5.2.11 on 2026-04-14 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rubrics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question_type", models.CharField(max_length=31)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("SHORT_ANSWER", "Short Answer"),
                            ("NUMBER_SCALE", "Number Scale"),
                            ("MOOD_METER", "Mood Meter"),
                            ("FILE_UPLOAD", "File Upload"),
                        ],
                        db_column="type",
                        max_length=255,
                    ),
                ),
                ("prompt", models.TextField()),
                ("max_points", models.FloatField()),
                ("auto_gradable", models.BooleanField(default=False)),
                ("graded", models.BooleanField(default=False)),
                ("image", models.TextField(blank=True, null=True)),
                (
                    "grading_strategy",
                    models.CharField(
                        choices=[("AUTO", "Auto"), ("MANUAL", "Manual")],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="AssignmentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "grading_mode",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto"),
                            ("MANUAL", "Manual"),
                            ("HYBRID", "Hybrid"),
                            ("MOOD_METER", "Mood Meter"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "submission_mode",
                    models.CharField(
                        choices=[
                            ("DIGITAL", "Digital"),
                            ("UPLOAD_ONLY", "Upload Only"),
                            ("DIGITAL_WITH_UPLOAD", "Digital with Upload"),
                        ],
                        default="DIGITAL",
                        max_length=32,
                    ),
                ),
                (
                    "scoring_policy",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("COMPLETION", "Completion")],
                        default="STANDARD",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_assignment_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_admin",
                    models.ForeignKey(
                        db_column="created_by_admin_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_assignment_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_templates",
                        to="rubrics.rubric",
                    ),
                ),
            ],
            options={
                "db_table": "assignment_templates",
            },
        ),
        migrations.CreateModel(
            name="AssignmentTemplateQuestionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order_index", models.IntegerField(default=0)),
                (
                    "assignment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_groups",
                        to="assignment_templates.assignmenttemplate",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_groups",
                        to="rubrics.rubric",
                    ),
                ),
            ],
            options={
                "db_table": "assignment_template_question_groups",
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "question",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="multiple_choice",
                        serialize=False,
                        to="assignment_templates.question",
                    ),
                ),
                ("select_all", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "multiple_choice_question",
            },
        ),
        migrations.CreateModel(
            name="NumberScaleQuestion",
            fields=[
                (
                    "question",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="number_scale",
                        serialize=False,
                        to="assignment_templates.question",
                    ),
                ),
                ("min", models.IntegerField()),
                ("max", models.IntegerField()),
                ("target", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "number_scale_question",
            },
        ),
        migrations.CreateModel(
            name="ShortAnswerQuestion",
            fields=[
                (
                    "question",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="short_answer",
                        serialize=False,
                        to="assignment_templates.question",
                    ),
                ),
                ("case_sensitive", models.BooleanField(default=False)),
                ("trim", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "short_answer_question",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="assignment_template",
            field=models.ForeignKey(
                blank=True,
                db_column="assignment_template_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="assignment_templates.assignmenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="assignment_templates.assignmenttemplatequestiongroup",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="rubrics.rubric",
            ),
        ),
        migrations.CreateModel(
            name="McqCorrectAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("correct_index", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcq_correct_answers",
                        to="assignment_templates.question",
                    ),
                ),
            ],
            options={
                "db_table": "mcq_correct_answers",
            },
        ),
        migrations.CreateModel(
            name="McqChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("choice_text", models.CharField(max_length=255)),
                ("points", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcq_choices",
                        to="assignment_templates.question",
                    ),
                ),
            ],
            options={
                "db_table": "mcq_choices",
            },
        ),
        migrations.AddIndex(
            model_name="assignmenttemplate",
            index=models.Index(fields=["status"], name="idx_assignment_template_status"),
        ),
    ]
