@startuml
autonumber
participant Client
database Postgres
participant eel-backend

Client ->> eel-backend: GET api/v1/auth/teachers-admins
eel-backend ->> Postgres: SELECT "app_users"."id", "app_users"."last_login", "app_users"."is_superuser", "app_users"."username", "app_users"."name", "app_users"."enabled", "app_users"."is_staff", "app_users"."created_at", "app_users"."updated_at", "app_users"."password_hash" FROM "app_users" WHERE "app_users"."id" = %s LIMIT 21
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s
eel-backend ->> Postgres: SELECT DISTINCT "app_users"."id", "app_users"."last_login", "app_users"."is_superuser", "app_users"."username", "app_users"."name", "app_users"."enabled", "app_users"."is_staff", "app_users"."created_at", "app_users"."updated_at", "app_users"."password_hash" FROM "app_users" INNER JOIN "user_roles" ON ("app_users"."id" = "user_roles"."user_id") WHERE "user_roles"."role" IN (%s, %s)
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s ORDER BY "user_roles"."id" ASC LIMIT 1
@enduml
