@startuml
autonumber
participant Client
database Postgres
participant "eel-backend"

Client ->> "eel-backend": POST api/v1/enrollments
"eel-backend" ->> Postgres: SELECT app_users WHERE id = ?
"eel-backend" ->> Postgres: SELECT user_roles WHERE user_id = ?
"eel-backend" ->> Postgres: SELECT registration_codes WHERE code_hash = ?
"eel-backend" ->> Postgres: SELECT courses WHERE id = ?
"eel-backend" ->> Postgres: SELECT student_profiles WHERE user_id = ?
"eel-backend" ->> Postgres: SELECT enrollments WHERE course_id = ?
"eel-backend" -->> Client: HTTP 201
@enduml
