@startuml
autonumber
participant Client
database Postgres
participant "eel-backend"

Client ->> "eel-backend": POST api/v1/registration/code-validations
"eel-backend" ->> Postgres: SELECT registration_codes WHERE code_hash = ?
"eel-backend" --x Client: HTTP 400
@enduml
