# Generated by Django 5.2.12 on 2026-03-04 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_course_lifecycle_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageBuildJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("strict_mode", models.BooleanField(default=True)),
                ("snapshot_id", models.IntegerField(blank=True, null=True)),
                ("mode", models.CharField(default="live", max_length=8)),
                ("error_message", models.TextField(blank=True, default="")),
                ("warnings", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_build_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "package_build_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_path", models.CharField(max_length=512)),
                ("file_size", models.BigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("manifest", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build_job",
                    models.OneToOneField(
                        db_column="build_job_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact",
                        to="packages.packagebuildjob",
                    ),
                ),
            ],
            options={
                "db_table": "package_artifacts",
            },
        ),
        migrations.CreateModel(
            name="PackageWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("SEALED", "Sealed")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scope_course",
                    models.ForeignKey(
                        blank=True,
                        db_column="scope_course_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_workspaces",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "package_workspaces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[("FOLDER", "Folder"), ("FILE", "File")], max_length=8
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "dataset_binding",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROSTER", "Roster"),
                            ("COURSE_SUBMISSIONS", "Course Submissions"),
                            ("CROSS_COURSE_SUBMISSIONS", "Cross-Course Submissions"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("binding_course_id", models.IntegerField(blank=True, null=True)),
                ("filters", models.JSONField(blank=True, null=True)),
                ("identifiable", models.BooleanField(default=False)),
                ("include_answers", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="packages.packagenode",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="packages.packageworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "package_nodes",
                "ordering": ["order_index", "id"],
            },
        ),
        migrations.AddField(
            model_name="packagebuildjob",
            name="workspace",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="build_jobs",
                to="packages.packageworkspace",
            ),
        ),
        migrations.CreateModel(
            name="PackageAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("WORKSPACE_CREATE", "Workspace Create"),
                            ("WORKSPACE_UPDATE", "Workspace Update"),
                            ("NODE_ADD", "Node Add"),
                            ("NODE_UPDATE", "Node Update"),
                            ("NODE_DELETE", "Node Delete"),
                            ("VALIDATE", "Validate"),
                            ("BUILD", "Build"),
                            ("DOWNLOAD", "Download"),
                        ],
                        max_length=32,
                    ),
                ),
                ("scope", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("DENIED", "Denied"),
                        ],
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        db_column="workspace_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="packages.packageworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "package_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
