# Generated by Django 5.2.12 on 2026-03-05 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="packagenode",
            name="source_type",
            field=models.CharField(
                choices=[("LIVE", "Live"), ("SNAPSHOT", "Snapshot")], default="LIVE", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="packageauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("WORKSPACE_CREATE", "Workspace Create"),
                    ("WORKSPACE_UPDATE", "Workspace Update"),
                    ("NODE_ADD", "Node Add"),
                    ("NODE_UPDATE", "Node Update"),
                    ("NODE_DELETE", "Node Delete"),
                    ("NODE_REORDER", "Node Reorder"),
                    ("VALIDATE", "Validate"),
                    ("BUILD", "Build"),
                    ("DOWNLOAD", "Download"),
                    ("SNAPSHOT_CREATE", "Snapshot Create"),
                    ("SNAPSHOT_EXPIRE", "Snapshot Expire"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DataSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dataset_binding",
                    models.CharField(
                        choices=[
                            ("ROSTER", "Roster"),
                            ("COURSE_SUBMISSIONS", "Course Submissions"),
                            ("CROSS_COURSE_SUBMISSIONS", "Cross-Course Submissions"),
                        ],
                        max_length=32,
                    ),
                ),
                ("scope_course_id", models.IntegerField(blank=True, null=True)),
                ("filters", models.JSONField(blank=True, null=True)),
                ("include_answers", models.BooleanField(default=False)),
                ("identifiable", models.BooleanField(default=False)),
                ("storage_key", models.CharField(blank=True, default="", max_length=512)),
                ("row_count", models.IntegerField(default=0)),
                ("file_size", models.BigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="packages.packageworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "data_snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="packagenode",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                db_column="snapshot_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nodes",
                to="packages.datasnapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="datasnapshot",
            index=models.Index(fields=["workspace", "status"], name="idx_snap_ws_status"),
        ),
        migrations.AddIndex(
            model_name="datasnapshot",
            index=models.Index(fields=["created_by", "created_at"], name="idx_snap_creator"),
        ),
        migrations.AddIndex(
            model_name="datasnapshot",
            index=models.Index(fields=["expires_at"], name="idx_snap_expires"),
        ),
    ]
