# Generated by Django 5.2.12 on 2026-03-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_packagenode_source_type_alter_packageauditlog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("WORKSPACE_CREATE", "Workspace Create"),
                    ("WORKSPACE_UPDATE", "Workspace Update"),
                    ("WORKSPACE_DELETE", "Workspace Delete"),
                    ("NODE_ADD", "Node Add"),
                    ("NODE_UPDATE", "Node Update"),
                    ("NODE_DELETE", "Node Delete"),
                    ("NODE_REORDER", "Node Reorder"),
                    ("VALIDATE", "Validate"),
                    ("BUILD", "Build"),
                    ("DOWNLOAD", "Download"),
                    ("SNAPSHOT_CREATE", "Snapshot Create"),
                    ("SNAPSHOT_EXPIRE", "Snapshot Expire"),
                ],
                max_length=32,
            ),
        ),
    ]
