@startuml
autonumber
participant Client
database Postgres
participant eel-backend

Client ->> eel-backend: PUT api/v1/assessments/<int:assessment_id>
eel-backend ->> Postgres: SELECT "app_users"."id", "app_users"."last_login", "app_users"."is_superuser", "app_users"."username", "app_users"."name", "app_users"."enabled", "app_users"."is_staff", "app_users"."created_at", "app_users"."updated_at", "app_users"."password_hash" FROM "app_users" WHERE "app_users"."id" = %s LIMIT 21
eel-backend ->> Postgres: SELECT "assessments"."id", "assessments"."title", "assessments"."category", "assessments"."grading_mode", "assessments"."created_by_admin_id", "assessments"."rubric_id", "assessments"."rubric_assessment_ids" FROM "assessments" WHERE "assessments"."id" = %s ORDER BY "assessments"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s
eel-backend ->> Postgres: UPDATE "assessments" SET "title" = %s, "category" = NULL, "grading_mode" = %s, "created_by_admin_id" = %s, "rubric_id" = NULL, "rubric_assessment_ids" = %s::bigint[] WHERE "assessments"."id" = %s
eel-backend ->> Postgres: SELECT "questions"."id", "questions"."question_type", "questions"."type", "questions"."assessment_id", "questions"."prompt", "questions"."max_points", "questions"."auto_gradable", "questions"."graded", "questions"."image" FROM "questions" WHERE "questions"."assessment_id" = %s
eel-backend ->> Postgres: SELECT "answer"."id" FROM "answer" WHERE "answer"."question_id" IN (%s)
eel-backend ->> Postgres: SELECT "multiple_choice_answer"."id" FROM "multiple_choice_answer" WHERE "multiple_choice_answer"."id" IN (%s, %s)
eel-backend ->> Postgres: DELETE FROM "short_answer_answer" WHERE "short_answer_answer"."id" IN (%s, %s)
eel-backend ->> Postgres: DELETE FROM "number_scale_answer" WHERE "number_scale_answer"."id" IN (%s, %s)
eel-backend ->> Postgres: DELETE FROM "mood_meter_answer" WHERE "mood_meter_answer"."id" IN (%s, %s)
eel-backend ->> Postgres: DELETE FROM "multiple_choice_question" WHERE "multiple_choice_question"."id" IN (%s)
eel-backend ->> Postgres: DELETE FROM "short_answer_question" WHERE "short_answer_question"."id" IN (%s)
eel-backend ->> Postgres: DELETE FROM "number_scale_question" WHERE "number_scale_question"."id" IN (%s)
eel-backend ->> Postgres: DELETE FROM "mood_meter_question" WHERE "mood_meter_question"."id" IN (%s)
eel-backend ->> Postgres: DELETE FROM "mcq_choices" WHERE "mcq_choices"."question_id" IN (%s)
eel-backend ->> Postgres: DELETE FROM "mcq_correct_answers" WHERE "mcq_correct_answers"."question_id" IN (%s)
eel-backend ->> Postgres: DELETE FROM "mood_meter_labels" WHERE "mood_meter_labels"."question_id" IN (%s)
eel-backend ->> Postgres: UPDATE "response" SET "question_id" = NULL WHERE "response"."question_id" IN (%s)
eel-backend ->> Postgres: DELETE FROM "answer" WHERE "answer"."id" IN (%s, %s)
eel-backend ->> Postgres: DELETE FROM "questions" WHERE "questions"."id" IN (%s)
eel-backend ->> Postgres: INSERT INTO "questions" ("question_type", "type", "assessment_id", "prompt", "max_points", "auto_gradable", "graded", "image") VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING "questions"."id"
eel-backend ->> Postgres: INSERT INTO "short_answer_question" ("id", "case_sensitive", "trim") VALUES (%s, %s, %s)
eel-backend ->> Postgres: SELECT "questions"."id", "questions"."question_type", "questions"."type", "questions"."assessment_id", "questions"."prompt", "questions"."max_points", "questions"."auto_gradable", "questions"."graded", "questions"."image" FROM "questions" WHERE "questions"."assessment_id" = %s
eel-backend ->> Postgres: SELECT "short_answer_question"."id", "short_answer_question"."case_sensitive", "short_answer_question"."trim" FROM "short_answer_question" WHERE "short_answer_question"."id" = %s LIMIT 21
@enduml
