@startuml
autonumber
participant Client
database Postgres
participant eel-backend

Client ->> eel-backend: POST api/v1/assessments/<int:assessment_id>/teacher-self-assess
eel-backend ->> Postgres: SELECT "app_users"."id", "app_users"."last_login", "app_users"."is_superuser", "app_users"."username", "app_users"."name", "app_users"."enabled", "app_users"."is_staff", "app_users"."created_at", "app_users"."updated_at", "app_users"."password_hash" FROM "app_users" WHERE "app_users"."id" = %s LIMIT 21
eel-backend ->> Postgres: SELECT "assessments"."id", "assessments"."title", "assessments"."category", "assessments"."grading_mode", "assessments"."created_by_admin_id", "assessments"."rubric_id", "assessments"."rubric_assessment_ids" FROM "assessments" WHERE "assessments"."id" = %s ORDER BY "assessments"."id" ASC LIMIT 1
eel-backend ->> Postgres: INSERT INTO "assignments" ("assessment_id", "audience_type", "course_id", "created_by_user_id", "open_at", "due_at", "teacher_id") VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING "assignments"."id"
eel-backend ->> Postgres: INSERT INTO "submissions" ("assignment_id", "score", "status", "student_id", "teacher_id", "submitted_at") VALUES (%s, %s, %s, %s, %s, %s) RETURNING "submissions"."id"
eel-backend ->> Postgres: SELECT "answer"."id", "answer"."answer_type", "answer"."question_id", "answer"."submission_id", "answer"."score", "answer"."skipped" FROM "answer" WHERE "answer"."submission_id" = %s
eel-backend ->> Postgres: SELECT "questions"."id", "questions"."question_type", "questions"."type", "questions"."assessment_id", "questions"."prompt", "questions"."max_points", "questions"."auto_gradable", "questions"."graded", "questions"."image" FROM "questions" WHERE "questions"."id" = %s ORDER BY "questions"."id" ASC LIMIT 1
eel-backend ->> Postgres: INSERT INTO "answer" ("answer_type", "question_id", "submission_id", "score", "skipped") VALUES (%s, %s, %s, %s, %s) RETURNING "answer"."id"
eel-backend ->> Postgres: INSERT INTO "short_answer_answer" ("id", "text") VALUES (%s, %s)
eel-backend ->> Postgres: UPDATE "submissions" SET "assignment_id" = %s, "score" = NULL, "status" = %s, "student_id" = NULL, "teacher_id" = %s, "submitted_at" = %s WHERE "submissions"."id" = %s
eel-backend ->> Postgres: SELECT "answer"."id", "answer"."answer_type", "answer"."question_id", "answer"."submission_id", "answer"."score", "answer"."skipped" FROM "answer" WHERE "answer"."submission_id" = %s
eel-backend ->> Postgres: SELECT "short_answer_answer"."id", "short_answer_answer"."text" FROM "short_answer_answer" WHERE "short_answer_answer"."id" = %s LIMIT 21
@enduml
