@startuml
autonumber
participant Client
database Postgres
participant eel-backend

Client ->> eel-backend: POST api/v1/assessments/
eel-backend ->> Postgres: SELECT "app_users"."id", "app_users"."last_login", "app_users"."is_superuser", "app_users"."username", "app_users"."name", "app_users"."enabled", "app_users"."is_staff", "app_users"."created_at", "app_users"."updated_at", "app_users"."password_hash" FROM "app_users" WHERE "app_users"."id" = %s LIMIT 21
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s
eel-backend ->> Postgres: INSERT INTO "assessments" ("title", "category", "grading_mode", "created_by_admin_id", "rubric_id", "rubric_assessment_ids") VALUES (%s, %s, %s, %s, %s, %s::bigint[]) RETURNING "assessments"."id"
eel-backend ->> Postgres: SELECT "questions"."id", "questions"."question_type", "questions"."type", "questions"."assessment_id", "questions"."prompt", "questions"."max_points", "questions"."auto_gradable", "questions"."graded", "questions"."image" FROM "questions" WHERE "questions"."assessment_id" = %s
eel-backend ->> Postgres: INSERT INTO "questions" ("question_type", "type", "assessment_id", "prompt", "max_points", "auto_gradable", "graded", "image") VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING "questions"."id"
eel-backend ->> Postgres: INSERT INTO "short_answer_question" ("id", "case_sensitive", "trim") VALUES (%s, %s, %s)
eel-backend ->> Postgres: SELECT "questions"."id", "questions"."question_type", "questions"."type", "questions"."assessment_id", "questions"."prompt", "questions"."max_points", "questions"."auto_gradable", "questions"."graded", "questions"."image" FROM "questions" WHERE "questions"."assessment_id" = %s
eel-backend ->> Postgres: SELECT "short_answer_question"."id", "short_answer_question"."case_sensitive", "short_answer_question"."trim" FROM "short_answer_question" WHERE "short_answer_question"."id" = %s LIMIT 21
@enduml
