@startuml
autonumber
participant Client
database Postgres
participant eel-backend

Client ->> eel-backend: DELETE api/v1/assessments/<int:assessment_id>
eel-backend ->> Postgres: SELECT "app_users"."id", "app_users"."last_login", "app_users"."is_superuser", "app_users"."username", "app_users"."name", "app_users"."enabled", "app_users"."is_staff", "app_users"."created_at", "app_users"."updated_at", "app_users"."password_hash" FROM "app_users" WHERE "app_users"."id" = %s LIMIT 21
eel-backend ->> Postgres: SELECT "assessments"."id", "assessments"."title", "assessments"."category", "assessments"."grading_mode", "assessments"."created_by_admin_id", "assessments"."rubric_id", "assessments"."rubric_assessment_ids" FROM "assessments" WHERE "assessments"."id" = %s ORDER BY "assessments"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s
eel-backend ->> Postgres: SELECT "assignments"."id", "assignments"."assessment_id", "assignments"."audience_type", "assignments"."course_id", "assignments"."created_by_user_id", "assignments"."open_at", "assignments"."due_at", "assignments"."teacher_id" FROM "assignments" WHERE "assignments"."assessment_id" = %s
eel-backend ->> Postgres: SELECT "assignments"."id" FROM "assignments" WHERE "assignments"."assessment_id" IN (%s)
eel-backend ->> Postgres: UPDATE "assessments" SET "rubric_id" = NULL WHERE "assessments"."rubric_id" IN (%s)
eel-backend ->> Postgres: UPDATE "questions" SET "assessment_id" = NULL WHERE "questions"."assessment_id" IN (%s)
eel-backend ->> Postgres: DELETE FROM "assessments" WHERE "assessments"."id" IN (%s)
@enduml
