@startuml
autonumber
participant Client
database Postgres
participant eel-backend

Client ->> eel-backend: GET api/v1/assessments/<int:assessment_id>
eel-backend ->> Postgres: SELECT "app_users"."id", "app_users"."last_login", "app_users"."is_superuser", "app_users"."username", "app_users"."name", "app_users"."enabled", "app_users"."is_staff", "app_users"."created_at", "app_users"."updated_at", "app_users"."password_hash" FROM "app_users" WHERE "app_users"."id" = %s LIMIT 21
eel-backend ->> Postgres: SELECT "assessments"."id", "assessments"."title", "assessments"."category", "assessments"."grading_mode", "assessments"."created_by_admin_id", "assessments"."rubric_id", "assessments"."rubric_assessment_ids" FROM "assessments" WHERE "assessments"."id" = %s ORDER BY "assessments"."id" ASC LIMIT 1
eel-backend ->> Postgres: SELECT "user_roles"."role" AS "role" FROM "user_roles" WHERE "user_roles"."user_id" = %s
eel-backend ->> Postgres: SELECT %s AS "a" FROM "assignments" WHERE ("assignments"."assessment_id" = %s AND "assignments"."course_id" IN (SELECT U0."course_id" AS "course_id" FROM "enrollments" U0 INNER JOIN "student_profiles" U1 ON (U0."student_profile_id" = U1."id") WHERE U1."user_id" = %s)) LIMIT 1
eel-backend ->> Postgres: SELECT "questions"."id", "questions"."question_type", "questions"."type", "questions"."assessment_id", "questions"."prompt", "questions"."max_points", "questions"."auto_gradable", "questions"."graded", "questions"."image" FROM "questions" WHERE "questions"."assessment_id" = %s
eel-backend ->> Postgres: SELECT "short_answer_question"."id", "short_answer_question"."case_sensitive", "short_answer_question"."trim" FROM "short_answer_question" WHERE "short_answer_question"."id" = %s LIMIT 21
@enduml
