# Generated by Django 5.2.11 on 2026-03-02 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rubrics",
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("order_index", models.IntegerField()),
                ("weight", models.FloatField(default=1.0)),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="rubrics.rubric",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_criteria",
            },
        ),
        migrations.CreateModel(
            name="RubricLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("points", models.FloatField()),
                ("description", models.TextField(blank=True, default="")),
                ("order_index", models.IntegerField()),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="rubrics.rubriccriterion",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_levels",
            },
        ),
        migrations.AddConstraint(
            model_name="rubriccriterion",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gt", 0)), name="rubric_criterion_weight_positive"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rubriccriterion",
            unique_together={("rubric", "order_index")},
        ),
        migrations.AddConstraint(
            model_name="rubriclevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("points__gte", 0)), name="rubric_level_points_non_negative"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rubriclevel",
            unique_together={("criterion", "order_index")},
        ),
    ]
