# Generated by Django 5.2.10 on 2026-01-18 06:03
"""Initial schema for assignment records."""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create initial assignment tables."""

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[("COURSE", "Course"), ("TEACHER", "Teacher")], max_length=255
                    ),
                ),
                ("open_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        db_column="assessment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "db_table": "assignments",
            },
        ),
    ]
