# Generated by Django 5.2.11 on 2026-04-14 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignment_templates", "0001_initial"),
        ("courses", "0002_course_lifecycle_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "audience_type",
                    models.CharField(
                        choices=[("COURSE", "Course"), ("TEACHER", "Teacher")], max_length=255
                    ),
                ),
                ("open_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment_template",
                    models.ForeignKey(
                        db_column="assignment_template_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assignment_templates.assignmenttemplate",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        db_column="course_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        db_column="teacher_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assignments",
                "indexes": [models.Index(fields=["status"], name="idx_assignment_status")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("audience_type", "COURSE"), _negated=True),
                            ("course_id__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_assignment_course_required_for_course_audience",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("audience_type", "TEACHER"), _negated=True),
                            ("course_id__isnull", True),
                            _connector="OR",
                        ),
                        name="ck_assignment_no_course_for_teacher_audience",
                    ),
                ],
            },
        ),
    ]
