# Generated by Django 5.2.10 on 2026-01-18 06:03
"""Add assignment relationships to courses and users."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add foreign-key relationships for assignments."""

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                db_column="course_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by_user_id",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                db_column="teacher_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
