# Generated by Django 5.2.11 on 2026-04-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentArchiveArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifiable", models.BooleanField(default=True)),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512, unique=True)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("sha256_hash", models.CharField(max_length=64)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_artifacts",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_assignment_archive_artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assignment_archive_artifacts",
                "indexes": [
                    models.Index(
                        fields=["assignment", "generated_at"],
                        name="idx_asgn_archive_artf",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assignment", "identifiable"),
                        name="uq_assignment_archive_artifact_variant",
                    )
                ],
            },
        ),
    ]
