# Generated by Django 5.2.11 on 2026-04-15 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment_templates", "0003_assignmenttemplate_has_been_used"),
        ("assignments", "0002_assignmentarchiveartifact"),
        ("core", "0004_add_imageasset_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentQuestionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order_index", models.IntegerField(default=0)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("TEMPLATE", "Template"),
                            ("TEACHER_ADDITION", "Teacher Addition"),
                        ],
                        default="TEMPLATE",
                        max_length=32,
                    ),
                ),
                ("locked_from_source", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_groups",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "source_template_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_group_snapshots",
                        to="assignment_templates.assignmenttemplatequestiongroup",
                    ),
                ),
            ],
            options={
                "db_table": "assignment_question_groups",
            },
        ),
        migrations.CreateModel(
            name="AssignmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("SHORT_ANSWER", "Short Answer"),
                            ("NUMBER_SCALE", "Number Scale"),
                            ("MOOD_METER", "Mood Meter"),
                            ("FILE_UPLOAD", "File Upload"),
                        ],
                        db_column="type",
                        max_length=255,
                    ),
                ),
                ("prompt", models.TextField()),
                ("max_points", models.FloatField()),
                ("auto_gradable", models.BooleanField(default=False)),
                ("graded", models.BooleanField(default=False)),
                ("image", models.TextField(blank=True, null=True)),
                (
                    "grading_strategy",
                    models.CharField(
                        choices=[("AUTO", "Auto"), ("MANUAL", "Manual")],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("order_index", models.IntegerField(default=0)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("TEMPLATE", "Template"),
                            ("TEACHER_ADDITION", "Teacher Addition"),
                        ],
                        default="TEMPLATE",
                        max_length=32,
                    ),
                ),
                ("locked_from_source", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_questions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_questions",
                        to="core.imageasset",
                    ),
                ),
                (
                    "source_template_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_question_snapshots",
                        to="assignment_templates.question",
                    ),
                ),
                (
                    "question_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="assignments.assignmentquestiongroup",
                    ),
                ),
            ],
            options={
                "db_table": "assignment_questions",
            },
        ),
        migrations.CreateModel(
            name="AssignmentTeacherCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("weight", models.FloatField(default=1.0)),
                ("order_index", models.IntegerField(default=0)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_criteria",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_teacher_criteria_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assignment_teacher_criteria",
            },
        ),
        migrations.AddIndex(
            model_name="assignmentquestiongroup",
            index=models.Index(fields=["assignment", "order_index"], name="idx_asgn_qgroup_order"),
        ),
        migrations.AddIndex(
            model_name="assignmentquestion",
            index=models.Index(
                fields=["assignment", "order_index"], name="idx_asgn_question_order"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentquestion",
            index=models.Index(fields=["origin"], name="idx_asgn_question_origin"),
        ),
        migrations.AddIndex(
            model_name="assignmentteachercriterion",
            index=models.Index(
                fields=["assignment", "order_index"], name="idx_asgn_criterion_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmentteachercriterion",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gt", 0)),
                name="ck_assignment_teacher_criterion_weight_positive",
            ),
        ),
    ]
