# Generated by Django 5.2.11 on 2026-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_assignment_status_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
