# Generated by Django 5.2.11 on 2026-04-15 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_assignmentquestiongroup_assignmentquestion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentTeacherCriterionLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("points", models.FloatField()),
                ("description", models.TextField(blank=True, default="")),
                ("order_index", models.IntegerField(default=0)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="assignments.assignmentteachercriterion",
                    ),
                ),
            ],
            options={
                "db_table": "assignment_teacher_criterion_levels",
            },
        ),
        migrations.AddIndex(
            model_name="assignmentteachercriterionlevel",
            index=models.Index(
                fields=["criterion", "order_index"],
                name="idx_asgn_criterion_level_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmentteachercriterionlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("points__gte", 0)),
                name="ck_assignment_teacher_criterion_level_points_non_negative",
            ),
        ),
    ]
