# Generated by Django 5.2.12 on 2026-03-30 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_assessment_archival_metadata"),
        ("assignments", "0005_assignment_archival_metadata"),
        ("courses", "0002_course_lifecycle_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("audience_type", "COURSE"), _negated=True),
                    ("course_id__isnull", False),
                    _connector="OR",
                ),
                name="ck_assignment_course_required_for_course_audience",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("audience_type", "TEACHER"), _negated=True),
                    ("course_id__isnull", True),
                    _connector="OR",
                ),
                name="ck_assignment_no_course_for_teacher_audience",
            ),
        ),
    ]
