# Generated by Django 5.2.12 on 2026-03-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_image_audit_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("SUDO_GRANT", "Sudo Grant"),
                    ("SUDO_REVOKE", "Sudo Revoke"),
                    ("ROLE_CHANGE", "Role Change"),
                    ("USER_DELETE", "User Delete"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("SCORE_OVERRIDE", "Score Override"),
                    ("ARCHIVE", "Archive"),
                    ("RESTORE", "Restore"),
                    ("PURGE", "Purge"),
                    ("IMAGE_UPLOAD", "Image Upload"),
                    ("IMAGE_PROXY_UPLOAD", "Image Proxy Upload"),
                    ("IMAGE_DELETE", "Image Delete"),
                    ("PKG_BUILD", "Pkg Build"),
                    ("PKG_DOWNLOAD", "Pkg Download"),
                ],
                max_length=32,
            ),
        ),
    ]
