# Generated by Django 5.2.13 on 2026-04-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_imageasset_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("SUDO_GRANT", "Sudo Grant"),
                    ("SUDO_REVOKE", "Sudo Revoke"),
                    ("ROLE_CHANGE", "Role Change"),
                    ("USER_DELETE", "User Delete"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("SCORE_OVERRIDE", "Score Override"),
                    ("ARCHIVE", "Archive"),
                    ("RESTORE", "Restore"),
                    ("PURGE", "Purge"),
                    ("IMAGE_UPLOAD", "Image Upload"),
                    ("IMAGE_PROXY_UPLOAD", "Image Proxy Upload"),
                    ("IMAGE_DELETE", "Image Delete"),
                ],
                max_length=32,
            ),
        ),
    ]
