# Generated by Django 5.2.10 on 2026-02-03 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("RESEARCHER", "Researcher"),
                    ("TEACHER", "Teacher"),
                    ("STUDENT", "Student"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SudoGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("can_grant_sudo", models.BooleanField(default=False)),
                ("permissions", models.JSONField(default=list)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sudo_grants_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sudo_grant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sudo_grants",
            },
        ),
        migrations.CreateModel(
            name="ResearcherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researcher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "researcher_profiles",
                "constraints": [
                    models.UniqueConstraint(fields=("user",), name="uq_researcher_user")
                ],
            },
        ),
    ]
