# Generated by Django 5.2.11 on 2026-02-13 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_researcher_profile_and_sudo_grant"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=320, unique=True),
        ),
        migrations.CreateModel(
            name="RegistrationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("TEACHER", "Teacher"),
                            ("RESEARCHER", "Researcher"),
                        ],
                        max_length=32,
                    ),
                ),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        db_column="course_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_codes",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_codes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "registration_codes",
                "indexes": [
                    models.Index(fields=["code"], name="idx_registration_code"),
                    models.Index(fields=["code_type"], name="idx_registration_code_type"),
                    models.Index(fields=["course"], name="idx_registration_course"),
                    models.Index(fields=["expires_at"], name="idx_registration_expires"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="uq_registration_code")
                ],
            },
        ),
    ]
