# Generated by Django 5.2.11 on 2026-02-13 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_username_registrationcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(max_length=320)),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("RESEARCHER", "Researcher"),
                            ("TEACHER", "Teacher"),
                            ("STUDENT", "Student"),
                        ],
                        max_length=32,
                    ),
                ),
                ("request_token_hash", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="reviewed_by_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="password_reset_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_requests",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_hash", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.OneToOneField(
                        db_column="request_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_code",
                        to="accounts.passwordresetrequest",
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_codes",
            },
        ),
        migrations.AddIndex(
            model_name="passwordresetrequest",
            index=models.Index(fields=["identifier"], name="idx_prr_identifier"),
        ),
        migrations.AddIndex(
            model_name="passwordresetrequest",
            index=models.Index(fields=["status"], name="idx_prr_status"),
        ),
        migrations.AddIndex(
            model_name="passwordresetrequest",
            index=models.Index(fields=["expires_at"], name="idx_prr_expires_at"),
        ),
        migrations.AddIndex(
            model_name="passwordresetrequest",
            index=models.Index(fields=["user"], name="idx_prr_user"),
        ),
        migrations.AddIndex(
            model_name="passwordresetcode",
            index=models.Index(fields=["expires_at"], name="idx_prc_expires_at"),
        ),
        migrations.AddIndex(
            model_name="passwordresetcode",
            index=models.Index(fields=["used_at"], name="idx_prc_used_at"),
        ),
    ]
