# Generated by Django 5.2.11 on 2026-02-13 02:14

from django.db import migrations, models


def backfill_email_from_username(apps, schema_editor):
    """Populate email from legacy username values that were email-shaped."""
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(email__isnull=True):
        username = (user.username or "").strip().lower()
        if "@" not in username:
            continue
        user.email = username
        user.save(update_fields=["email"])


def noop_reverse(apps, schema_editor):
    """No-op reverse migration for one-way normalization."""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_passwordresetrequest_passwordresetcode_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=320, null=True),
        ),
        migrations.RunPython(backfill_email_from_username, noop_reverse),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="idx_user_email"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("email",),
                name="uq_user_email",
            ),
        ),
    ]
