# Generated by Django 5.2.11 on 2026-02-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_email_user_idx_user_email_user_uq_user_email"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationcode",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="registrationcode",
            index=models.Index(fields=["archived_at"], name="idx_registration_archived"),
        ),
    ]
