# Generated by Django 5.2.12 on 2026-03-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_registrationcode_metadata"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="registrationcode",
            name="idx_registration_code_hash",
        ),
    ]
