# Generated by Django 5.2.11 on 2026-04-14 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignment_templates", "0001_initial"),
        ("assignments", "0001_initial"),
        ("core", "0004_add_imageasset_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("SHORT_ANSWER", "Short Answer"),
                            ("NUMBER_SCALE", "Number Scale"),
                            ("MOOD_METER", "Mood Meter"),
                            ("FILE_UPLOAD", "File Upload"),
                        ],
                        max_length=31,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("skipped", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assignment_templates.question",
                    ),
                ),
            ],
            options={
                "db_table": "answer",
            },
        ),
        migrations.CreateModel(
            name="FileUploadAnswer",
            fields=[
                (
                    "answer",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="file_upload",
                        serialize=False,
                        to="submissions.answer",
                    ),
                ),
                ("storage_key", models.CharField(blank=True, default="", max_length=512)),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=64)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "file_upload_answer",
            },
        ),
        migrations.CreateModel(
            name="MoodMeterAnswer",
            fields=[
                (
                    "answer",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mood_meter",
                        serialize=False,
                        to="submissions.answer",
                    ),
                ),
                ("quadrant", models.CharField(blank=True, default="", max_length=64)),
                ("mood_name", models.CharField(blank=True, default="", max_length=64)),
                ("row", models.IntegerField(blank=True, null=True)),
                ("col", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "mood_meter_answer",
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceAnswer",
            fields=[
                (
                    "answer",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="multiple_choice",
                        serialize=False,
                        to="submissions.answer",
                    ),
                ),
            ],
            options={
                "db_table": "multiple_choice_answer",
            },
        ),
        migrations.CreateModel(
            name="NumberScaleAnswer",
            fields=[
                (
                    "answer",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="number_scale",
                        serialize=False,
                        to="submissions.answer",
                    ),
                ),
                ("val", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "number_scale_answer",
            },
        ),
        migrations.CreateModel(
            name="ShortAnswerAnswer",
            fields=[
                (
                    "answer",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="short_answer",
                        serialize=False,
                        to="submissions.answer",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "short_answer_answer",
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("skipped", models.BooleanField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        db_column="question_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="assignment_templates.question",
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        db_column="respondent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "response",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                            ("GRADED", "Graded"),
                        ],
                        max_length=255,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        db_column="assignment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_column="student_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        db_column="teacher_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="submission",
            field=models.ForeignKey(
                db_column="submission_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="submissions.submission",
            ),
        ),
        migrations.CreateModel(
            name="SubmissionImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("storage_key", models.CharField(max_length=512, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveIntegerField()),
                ("sha256_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_SCAN", "Pending Scan"),
                            ("READY", "Ready"),
                            ("REJECTED", "Rejected"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_column="asset_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission_images",
                        to="core.imageasset",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        db_column="submission_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="submissions.submission",
                    ),
                ),
                (
                    "submission_owner",
                    models.ForeignKey(
                        db_column="submission_owner_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_submission_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        db_column="uploaded_by_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submission_image",
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceSelected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("choice_index", models.IntegerField(blank=True, null=True)),
                (
                    "answer",
                    models.ForeignKey(
                        db_column="answer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected",
                        to="submissions.multiplechoiceanswer",
                    ),
                ),
            ],
            options={
                "db_table": "multiple_choice_selected",
            },
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("student_id__isnull", False), ("teacher_id__isnull", True)),
                    models.Q(("student_id__isnull", True), ("teacher_id__isnull", False)),
                    _connector="OR",
                ),
                name="ck_submission_owner_xor",
            ),
        ),
        migrations.AddIndex(
            model_name="submissionimage",
            index=models.Index(fields=["submission", "status"], name="idx_subimg_sub_status"),
        ),
        migrations.AddConstraint(
            model_name="submissionimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gt", 0)), name="ck_subimg_size_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "DELETED"), _negated=True),
                fields=("submission", "sha256_hash"),
                name="uq_subimg_hash_active",
            ),
        ),
    ]
