# Generated by Django 5.2.11 on 2026-03-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("MULTIPLE_CHOICE", "Multiple Choice"),
                    ("SHORT_ANSWER", "Short Answer"),
                    ("NUMBER_SCALE", "Number Scale"),
                ],
                max_length=31,
            ),
        ),
        migrations.DeleteModel(
            name="MoodMeterAnswer",
        ),
    ]
