# Generated by Django 5.2.11 on 2026-04-15 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_assignmentquestiongroup_assignmentquestion_and_more"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="assignments.assignmentquestion",
            ),
        ),
    ]
