# Generated by Django 5.2.12 on 2026-03-30 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assignments",
            "0006_assignment_ck_assignment_course_required_for_course_audience_and_more",
        ),
        ("submissions", "0003_submissionimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("student_id__isnull", False), ("teacher_id__isnull", True)),
                    models.Q(("student_id__isnull", True), ("teacher_id__isnull", False)),
                    _connector="OR",
                ),
                name="ck_submission_owner_xor",
            ),
        ),
    ]
