# Generated by Django 5.2.12 on 2026-04-01 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_imageasset_model"),
        ("submissions", "0004_submission_ck_submission_owner_xor"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionimage",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                db_column="asset_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_images",
                to="core.imageasset",
            ),
        ),
    ]
