# Generated by Django 5.2.12 on 2026-04-01 00:41

import uuid

from django.db import migrations


def backfill_image_assets(apps, schema_editor):
    """Create an ImageAsset for each existing SubmissionImage and link them."""
    ImageAsset = apps.get_model("core", "ImageAsset")
    SubmissionImage = apps.get_model("submissions", "SubmissionImage")

    for si in SubmissionImage.objects.filter(asset__isnull=True).iterator():
        # Map old statuses to new: READY/PENDING_SCAN -> ACTIVE, DELETED -> DELETED
        asset_status = "DELETED" if si.status == "DELETED" else "ACTIVE"

        asset = ImageAsset.objects.create(
            id=uuid.uuid4(),
            storage_key=si.storage_key,
            original_filename=si.original_filename,
            mime_type=si.mime_type,
            size_bytes=si.size_bytes,
            sha256_hash=si.sha256_hash,
            status=asset_status,
            created_by_id=si.uploaded_by_id,
            deleted_at=si.deleted_at,
        )
        si.asset = asset
        si.save(update_fields=["asset"])


def reverse_backfill(apps, schema_editor):
    """Remove all ImageAsset records and clear FKs (reverse of backfill)."""
    SubmissionImage = apps.get_model("submissions", "SubmissionImage")
    ImageAsset = apps.get_model("core", "ImageAsset")

    SubmissionImage.objects.update(asset=None)
    ImageAsset.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_add_asset_fk_to_submissionimage"),
        ("core", "0004_add_imageasset_model"),
    ]

    operations = [
        migrations.RunPython(backfill_image_assets, reverse_backfill),
    ]
