# Generated by Django 5.2.12 on 2026-04-02 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_backfill_imageasset_from_submissionimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodMeterAnswer",
            fields=[
                (
                    "answer",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mood_meter",
                        serialize=False,
                        to="submissions.answer",
                    ),
                ),
                ("quadrant", models.CharField(blank=True, default="", max_length=64)),
                ("mood_name", models.CharField(blank=True, default="", max_length=64)),
                ("row", models.IntegerField(blank=True, null=True)),
                ("col", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "mood_meter_answer",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("MULTIPLE_CHOICE", "Multiple Choice"),
                    ("SHORT_ANSWER", "Short Answer"),
                    ("NUMBER_SCALE", "Number Scale"),
                    ("MOOD_METER", "Mood Meter"),
                ],
                max_length=31,
            ),
        ),
    ]
