# Generated by Django 5.2.12 on 2026-04-02 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0007_moodmeteranswer_alter_answer_answer_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUploadAnswer",
            fields=[
                (
                    "answer",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="file_upload",
                        serialize=False,
                        to="submissions.answer",
                    ),
                ),
                ("storage_key", models.CharField(blank=True, default="", max_length=512)),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=64)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "file_upload_answer",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("MULTIPLE_CHOICE", "Multiple Choice"),
                    ("SHORT_ANSWER", "Short Answer"),
                    ("NUMBER_SCALE", "Number Scale"),
                    ("MOOD_METER", "Mood Meter"),
                    ("FILE_UPLOAD", "File Upload"),
                ],
                max_length=31,
            ),
        ),
    ]
