@startuml
autonumber
participant Client
database Postgres
participant "eel-backend"

Client ->> "eel-backend": GET api/v1/users/staff
"eel-backend" ->> Postgres: SELECT app_users WHERE id = ?
"eel-backend" ->> Postgres: SELECT (SELECT WHERE role = ?
"eel-backend" ->> Postgres: SELECT app_users WHERE role = ?
"eel-backend" ->> Postgres: SELECT user_roles WHERE user_id = ?
"eel-backend" -->> Client: HTTP 200
@enduml
